music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name ='index'),
    # /music/id
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='detail'),
    # /music/album/add
    url(r'album/add/$',views.AlbumCreate.as_view(), name= 'album-add'),
    # /music/album/2
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(), name= 'album-update'),
    # /music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(), name= 'album-delete'),
    # /music/register
    url(r'^register/$', views.UserFormView.as_view(), name ='register-user'),
]

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('detail',kwargs={'pk':self.pk})
        
    def __str__(self):
        return self.album_title + ' - ' + self.artist 

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title 

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username','email','password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserForm
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo'] 
    title = "Add Album"

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo'] 
    title = "Update Album"
    
class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'
    title = "Register"

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit = False)
            #normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns user objects
            user = authenticate(username = username ,password = password)
        
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('index')

        return render(request,self.template_name,{'form':form})

music/templates/music/album_form.html
{% extends "music/base.html" %}
{% block title%}{{view.title}}{% endblock %}
{% block albums_active %}active{% endblock  %}
 
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include "music/form_template.html" %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type='submit' class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Jigs{%endblock%}</title>
    {% load staticfiles%}
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
        <link rel="stylesheet" href="{% static 'music/style.css' %}" />
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>    
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header --> 
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span> 
                <span class="icon-bar"></span> 
                <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand" href="{% url 'index' %}" >Jigs</a>
        </div>
        <!--Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'index' %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body%}
{% endblock%}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html'%}
{% block title%} Album Details {%endblock%}
{% block body %}
    <img src="{{album.album_logo.url}}" width="500dp" height="300dp" alt="">
    <h1>{{album.album_title}}</h1>
    <h3>{{album.artist}}</h3>
        {% if error_message %}
            <p><strong>{{error_message}}</strong></p>
        {%endif%}
        {% for song in album.song_set.all %}
            {{song.song_title}}
            {% if song.is_favorite %}
                <p>*</p>
            {%endif%}
        {%endfor%}
{% endblock %}

music/templates/music/form_template.html
{% for field in form  %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}   

music/templates/music/index.html
{% extends 'music/base.html'%}
{% block body%}
{% block title %} Albums {% endblock %}
    <H1>Album List</H1>
    {% if all_albums %}
            {% for album in object_list %}
            <ul>
                <li>
                    <div class="card">
                        <img class="card-img-top" src="{{album.album_logo.url}}" alt="Card image cap" height="150dp" width="150dp" >
                        <div class="card-body">
                            <h4 class="card-title">{{album.album_title}}</h4>
                            <p class="card-text">{{album.album_artist}}</p>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'detail' album.id  %}">
                                <input type="hidden" name="album_id" value="{{album.album_id}}"/>
                                <button type="submit" class="btn btn-default">View</button>
                            </form>
                            <form action="{% url 'album-delete' album.id  %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{album.album_id}}"/>
                                <button type="submit" class="btn btn-default">Delete</button>
                            </form>
                            <form action="{% url 'album-update' album.id  %}" name = "update_form" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{album.album_id}}"/>
                                    <button type="submit" class="btn btn-default">Update</button>
                            </form>
                        </div>
                    </div>
                </li>
            </ul>
            <!--  <li><a href= {% url 'detail' album.id %}>{{album.album_title}}</a></li> -->
            {% endfor %}
    {% else %}
        <h2>You have no records in your database</h2>
    {%endif%}
{% endblock %}  

music/templates/music/registration_form.html
{% extends "music/base.html" %}
{% block title  %}{{view.title}}{% endblock %}
{% block albums_active %}active{% endblock  %}
 
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include "music/form_template.html" %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type='submit' class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}